### ISSUE TITLE
Problems with Odoo 10

### ISSUE THREAD

**Issue by johntian** [ingadhoc/multi-store#3]
I know that there are only branches for odoo 8&9,but I think the odoo 9 branch is suitable with odoo 10,too.
When I run it on odoo 10,it reported errors like this:
>Odoo
>Server Error
>Traceback (most recent call last):
>  File "/Users/franktian/odoo-env/odoo/http.py", line 640, in _handle_exception
>    return super(JsonRequest, self)._handle_exception(exception)
>  File "/Users/franktian/odoo-env/odoo/http.py", line 677, in dispatch
>    result = self._call_function(**self.params)
>  File "/Users/franktian/odoo-env/odoo/http.py", line 333, in _call_function
>    return checked_call(self.db, *args, **kwargs)
>  File "/Users/franktian/odoo-env/odoo/service/model.py", line 101, in wrapper
>    return f(dbname, *args, **kwargs)
>  File "/Users/franktian/odoo-env/odoo/http.py", line 326, in checked_call
>    result = self.endpoint(*a, **kw)
>  File "/Users/franktian/odoo-env/odoo/http.py", line 935, in __call__
>    return self.method(*args, **kw)
>  File "/Users/franktian/odoo-env/odoo/http.py", line 506, in response_wrap
>    response = f(*args, **kw)
>  File "/Users/franktian/odoo-env/addons/web/controllers/main.py", line 885, in call_kw
>    return self._call_kw(model, method, args, kwargs)
>  File "/Users/franktian/odoo-env/addons/web/controllers/main.py", line 877, in _call_kw
>    return call_kw(request.env[model], method, args, kwargs)
>  File "/Users/franktian/odoo-env/odoo/api.py", line 681, in call_kw
>    return call_kw_multi(method, model, args, kwargs)
>  File "/Users/franktian/odoo-env/odoo/api.py", line 668, in call_kw_multi
>    ids, args = args[0], args[1:]
>IndexError: list index out of range

Would you like to fix these problems or develop an odoo 10 version?
Thank you so much!

**Comment by jjscarafia** [comment]
Sorry but I believe we are going to skip v10 and go directly to v11. If you want to migrate, PR are wellcome.

**Comment by bnisevic** [comment]
How did you fix this issue? Because this would exist also on v11 and v12.

**Comment by jjscarafia** [comment]
mmm, I'm not ware of any issue with this modules on v11 or v12. If so, please report it with all the information so that we can replicate it.
BR
